# Redis Pod 自动发现示例
#
# 在 Redis Pod 上添加以下注解，Prometheus 会自动发现并监控
# 配合 k8s-prometheus-scrape-config.yaml 的方式二使用
#
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-cluster
  namespace: default
  labels:
    app: redis-cluster
spec:
  serviceName: redis-cluster
  replicas: 3
  selector:
    matchLabels:
      app: redis-cluster
  template:
    metadata:
      labels:
        app: redis-cluster
        # 用于 project 标签
        project: production
      annotations:
        # ============================================
        # 关键注解 - 启用 Prometheus 自动发现
        # ============================================
        redis.io/scrape: "true"
        redis.io/port: "6379"
        redis.io/project: "production"
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        command:
        - redis-server
        args:
        - --cluster-enabled
        - "yes"
        - --cluster-config-file
        - /data/nodes.conf
        - --cluster-node-timeout
        - "5000"
        - --appendonly
        - "yes"
        ports:
        - containerPort: 6379
          name: redis
        - containerPort: 16379
          name: cluster-bus
        volumeMounts:
        - name: data
          mountPath: /data
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          tcpSocket:
            port: redis
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 5
          periodSeconds: 5
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
---
# Headless Service for StatefulSet
apiVersion: v1
kind: Service
metadata:
  name: redis-cluster
  namespace: default
  labels:
    app: redis-cluster
    # 用于 Service Discovery 方式
    redis.io/scrape: "true"
    project: production
spec:
  clusterIP: None
  ports:
  - port: 6379
    targetPort: 6379
    name: redis
  - port: 16379
    targetPort: 16379
    name: cluster-bus
  selector:
    app: redis-cluster
---
# 带密码的 Redis 示例
apiVersion: v1
kind: Secret
metadata:
  name: redis-password
  namespace: default
type: Opaque
stringData:
  password: "your-secure-password"
---
# 单实例 Redis (主从模式)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-master
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      role: master
  template:
    metadata:
      labels:
        app: redis
        role: master
        project: myproject
      annotations:
        redis.io/scrape: "true"
        redis.io/port: "6379"
        redis.io/project: "myproject"
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        args:
        - --requirepass
        - $(REDIS_PASSWORD)
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-password
              key: password
        ports:
        - containerPort: 6379

