# Redis Exporter for Kubernetes - 集群监控
#
# 适用环境:
#   - Redis Cluster StatefulSet (如 redis-cluster-0 ~ redis-cluster-5)
#   - Headless Service: redis-cluster-headless
#   - Namespace: redis
#
# 部署步骤:
#   1. 如有密码，先创建 Secret (见下方)
#   2. kubectl apply -f k8s-redis-cluster-exporter.yaml
#   3. 验证: kubectl -n monitoring get pods -l app=redis-exporter
#
# 验证监控:
#   kubectl -n monitoring port-forward svc/redis-exporter 9121:9121
#   curl http://localhost:9121/metrics
#   curl "http://localhost:9121/scrape?target=redis://redis-cluster-0.redis-cluster-headless.redis:6379"
#
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
---
# Redis 密码 (如无密码可跳过此 Secret)
#
# 方式一: 直接创建
# kubectl -n monitoring create secret generic redis-exporter-secret \
#   --from-literal=REDIS_PASSWORD='your-password'
#
# 方式二: 应用此文件 (修改下方密码)
apiVersion: v1
kind: Secret
metadata:
  name: redis-exporter-secret
  namespace: monitoring
type: Opaque
stringData:
  REDIS_PASSWORD: ""  # 填入 Redis 密码，无密码则留空
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-exporter
  namespace: monitoring
  labels:
    app: redis-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-exporter
  template:
    metadata:
      labels:
        app: redis-exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9121"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 59000
        runAsGroup: 59000
      containers:
      - name: redis-exporter
        image: ghcr.io/kevin197011/redis_exporter:latest
        args:
          - "--redis.addr="
          - "--is-cluster=true"
          # 队列监控 (可选)
          # - "--check-single-keys=db0=queue:orders,db0=queue:tasks"
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-exporter-secret
              key: REDIS_PASSWORD
              optional: true
        ports:
        - name: metrics
          containerPort: 9121
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop: ["ALL"]
        livenessProbe:
          httpGet:
            path: /health
            port: metrics
          initialDelaySeconds: 5
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /health
            port: metrics
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: redis-exporter
  namespace: monitoring
  labels:
    app: redis-exporter
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 9121
    targetPort: metrics
  selector:
    app: redis-exporter
---
# ============================================
# Prometheus Operator - ServiceMonitor
# 监控 redis namespace 下的 6 节点 Redis Cluster
# ============================================
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis-cluster
  namespace: monitoring
  labels:
    app: redis-cluster
    release: kube-prometheus-stack  # 根据你的 Prometheus Operator label selector 调整
spec:
  selector:
    matchLabels:
      app: redis-exporter
  namespaceSelector:
    matchNames:
    - monitoring
  endpoints:
  # redis-cluster-0
  - port: metrics
    interval: 15s
    path: /scrape
    params:
      target: ["redis://redis-cluster-0.redis-cluster-headless.redis.svc.cluster.local:6379"]
    relabelings:
    - targetLabel: instance
      replacement: "redis-cluster-0:6379"
    - targetLabel: project
      replacement: "myapp-prod-redis-cluster"
  # redis-cluster-1
  - port: metrics
    interval: 15s
    path: /scrape
    params:
      target: ["redis://redis-cluster-1.redis-cluster-headless.redis.svc.cluster.local:6379"]
    relabelings:
    - targetLabel: instance
      replacement: "redis-cluster-1:6379"
    - targetLabel: project
      replacement: "myapp-prod-redis-cluster"
  # redis-cluster-2
  - port: metrics
    interval: 15s
    path: /scrape
    params:
      target: ["redis://redis-cluster-2.redis-cluster-headless.redis.svc.cluster.local:6379"]
    relabelings:
    - targetLabel: instance
      replacement: "redis-cluster-2:6379"
    - targetLabel: project
      replacement: "myapp-prod-redis-cluster"
  # redis-cluster-3
  - port: metrics
    interval: 15s
    path: /scrape
    params:
      target: ["redis://redis-cluster-3.redis-cluster-headless.redis.svc.cluster.local:6379"]
    relabelings:
    - targetLabel: instance
      replacement: "redis-cluster-3:6379"
    - targetLabel: project
      replacement: "myapp-prod-redis-cluster"
  # redis-cluster-4
  - port: metrics
    interval: 15s
    path: /scrape
    params:
      target: ["redis://redis-cluster-4.redis-cluster-headless.redis.svc.cluster.local:6379"]
    relabelings:
    - targetLabel: instance
      replacement: "redis-cluster-4:6379"
    - targetLabel: project
      replacement: "myapp-prod-redis-cluster"
  # redis-cluster-5
  - port: metrics
    interval: 15s
    path: /scrape
    params:
      target: ["redis://redis-cluster-5.redis-cluster-headless.redis.svc.cluster.local:6379"]
    relabelings:
    - targetLabel: instance
      replacement: "redis-cluster-5:6379"
    - targetLabel: project
      replacement: "myapp-prod-redis-cluster"
